apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/sergioarcos/quarkus-petclinic
  newTag: b16b1289232afa4bf976c2bcb85c55351161a50c
